# python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/10_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/10_edit10Truesig >>10.log 2>&1 &
# python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/11_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/11_edit10Truesig >>11.log 2>&1 &
# python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/12_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/12_edit10Truesig >>12.log 2>&1 &
python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/13_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/13_edit10Truesig >>13.log 2>&1 &
python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/14_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/14_edit10Truesig >>14.log 2>&1 &
python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/15_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/15_edit10Truesig >>15.log 2>&1 &
# python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/16_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/16_edit10Truesig >>16.log 2>&1 &
# python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/17_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/17_edit10Truesig >>17.log 2>&1 &
# python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/18_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/18_edit10Truesig >>18.log 2>&1 &
# python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/19_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/19_edit10Truesig >>19.log 2>&1 &
# python generatNoiselessSignal.py -i /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/edit_fasta/20_edit10.fasta -o /data1/2022/UMIDesign/FPS/data/TestdataForEditDist/DataForThreshold/20_edit10Truesig >>20.log 2>&1 &
