"""
Copyright 2018 Ryan Wick (rrwick@gmail.com)
https://github.com/rrwick/Deepbinner/
"""

native_start_kit_adapter = 'AATGTACTTCGTTCAGTTACGTATTGCT'
native_start_barcodes = {'01': 'AAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCT',
                         '02': 'AAGGTTAAACAGACGACTACAAACGGAATCGACAGCACCT',
                         '03': 'AAGGTTAACCTGGTAACTGGGACACAAGACTCCAGCACCT',
                         '04': 'AAGGTTAATAGGGAAACACGATAGAATCCGAACAGCACCT',
                         '05': 'AAGGTTAAAAGGTTACACAAACCCTGGACAAGCAGCACCT',
                         '06': 'AAGGTTAAGACTACTTTCTGCCTTTGCGAGAACAGCACCT',
                         '07': 'AAGGTTAAAAGGATTCATTCCCACGGTAACACCAGCACCT',
                         '08': 'AAGGTTAAACGTAACTTGGTTTGTTCCCTGAACAGCACCT',
                         '09': 'AAGGTTAAAACCAAGACTCGCTGTGCCTAGTTCAGCACCT',
                         '10': 'AAGGTTAAGAGAGGACAAAGGTTTCAACGCTTCAGCACCT',
                         '11': 'AAGGTTAATCCATTCCCTCCGATAGATGAAACCAGCACCT',
                         '12': 'AAGGTTAATCCGATTCTGCTTCTTTCTACCTGCAGCACCT'}


native_end_kit_adapter = 'AGCAATACGTAACTGAACG'  # truncated a bit off the end
native_end_barcodes = {'01': 'AGGTGCTGAAGAAAGTTGTCGGTGTCTTTGTGTTAACCTT',
                       '02': 'AGGTGCTGTCGATTCCGTTTGTAGTCGTCTGTTTAACCTT',
                       '03': 'AGGTGCTGGAGTCTTGTGTCCCAGTTACCAGGTTAACCTT',
                       '04': 'AGGTGCTGTTCGGATTCTATCGTGTTTCCCTATTAACCTT',
                       '05': 'AGGTGCTGCTTGTCCAGGGTTTGTGTAACCTTTTAACCTT',
                       '06': 'AGGTGCTGTTCTCGCAAAGGCAGAAAGTAGTCTTAACCTT',
                       '07': 'AGGTGCTGGTGTTACCGTGGGAATGAATCCTTTTAACCTT',
                       '08': 'AGGTGCTGTTCAGGGAACAAACCAAGTTACGTTTAACCTT',
                       '09': 'AGGTGCTGAACTAGGCACAGCGAGTCTTGGTTTTAACCTT',
                       '10': 'AGGTGCTGAAGCGTTGAAACCTTTGTCCTCTCTTAACCTT',
                       '11': 'AGGTGCTGGTTTCATCTATCGGAGGGAATGGATTAACCTT',
                       '12': 'AGGTGCTGCAGGTAGAAAGAAGCAGAATCGGATTAACCTT'}


rapid_start_kit_adapter = 'CGTTCAGTTACGTATTGCTGTTTTCGCATTTATCGTGAA'
rapid_start_barcodes = {'01': 'TATTGCTCACAAAGACACCGACAACTTTCTTGTTTTCGC',
                        '02': 'TATTGCTACAGACGACTACAAACGGAATCGAGTTTTCGC',
                        '03': 'TATTGCTCCTGGTAACTGGGACACAAGACTCGTTTTCGC',
                        '04': 'TATTGCTTAGGGAAACACGATAGAATCCGAAGTTTTCGC',
                        '05': 'TATTGCTAAGGTTACACAAACCCTGGACAAGGTTTTCGC',
                        '06': 'TATTGCTGACTACTTTCTGCCTTTGCGAGAAGTTTTCGC',
                        '07': 'TATTGCTAAGGATTCATTCCCACGGTAACACGTTTTCGC',
                        '08': 'TATTGCTACGTAACTTGGTTTGTTCCCTGAAGTTTTCGC',
                        '09': 'TATTGCTAACCAAGACTCGCTGTGCCTAGTTGTTTTCGC',
                        '10': 'TATTGCTGAGAGGACAAAGGTTTCAACGCTTGTTTTCGC',
                        '11': 'TATTGCTTCCATTCCCTCCGATAGATGAAACGTTTTCGC',
                        '12': 'TATTGCTTCCGATTCTGCTTCTTTCTACCTGGTTTTCGC'}
